# Site settings
title: Merge Conflicts
email: boone.greg@gmail.com	
description: "I accidentally a software developer, is that bad?"
baseurl: ""
url: "http://greg.harmsboone.org"
timezone: "America/New_York"

# Build settings
markdown: kramdown
permalink: pretty
